repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'c4a0b88' # v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'fc26039' # "v3.0.3"
    hooks:
      - id: prettier
        types_or: [css, html, markdown, ts]
