repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'cef0300' # v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'f62a70a' # latest archived version
    hooks:
      - id: prettier
        types_or: [css, html, markdown, ts]
